@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold

title Lookup EDI for an enrolled patient's GP

actor "Integrating application user" as User #CornflowerBlue
participant "Integrating application" as A #CornflowerBlue
participant "Enrolment SOAP service (NES)" as B #CornflowerBlue
participant "HPI FHIR API" as C #CornflowerBlue
|||
User -> A: Lookup EDI for patient's GP
activate A
A -> B: Get Enrolment
activate B
B -> A: Return enrolling org FacID
deactivate B
|||
A -> C: GET [host]/location/[FacID]
activate C
C -> A: Return Facility resource
deactivate C
|||
A -> A: Extract EDI from Location.telecom
A -> User: EDI Address found
deactivate A
|||
@enduml