id: CIRImms
canonical: http://example.org
name: CIRImmunization
title: CIR Immunisation API
description: Profile on the Immunization resource for exposing Covid Immunisation events from the CIR through CTIP
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
license: CC0-1.0
releaseLabel: ci-build
publisher: 
  name: Ministry of Health

menu:
  IG Home: index.html
  Profiles: profiles.html
  Table of Contents: toc.html
  Artifact Index: artifacts.html
  Links:
    FHIR Spec: new-tab http://hl7.org/fhir/R4/index.html
