id: CIRImms
canonical: http://example.org
name: sandbox
title: testing...
description: A monstrous frankenstein IG, loosely held together through the concept of "testing some stuff"
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
license: CC0-1.0
releaseLabel: ci-build
publisher: 
  name: Daniel

menu:
  IG Home: index.html
  A Menu: 
    A submenu-link: new-tab https://github.com
  Table of Contents: toc.html
  Artifacts: artifacts.html
  Links:
    FHIR Spec: new-tab http://hl7.org/fhir/R4/index.html
